---
- name: condition playbook
  hosts: all
  become: yes
  tasks:
    - name: install apache debian family
      command: apt install apache2 -y
      when: ansible_os_family == 'Debian'

      name: install httpd in redhat family
      command: yum install httpd -y
      when: ansible_os_family == 'RedHat'
...      