---
- name: Gather Facts and Print
  hosts: all
  gather_facts: true
  tasks:
    - name: Print Hostname
      debug:
        var: ansible_hostname

    - name: Print Operating System
      debug:
        var: ansible_distribution

    - name: Print IP Address
      debug:
        var: ansible_default_ipv4.address
...        