---
- name: adding multiple user
  hosts: all
  become: yes
  tasks:
    - name:
      user:
       name="{{item}}"
       state=present
      with_items:
           - samyak
           - yash
           - balu
...           

