---
- name: Install Nginx
  hosts: all
  become: true  

  tasks:
    - name: Update package cache
      package:
        name: "*"
        state: latest
      when: ansible_os_family == 'Debian'  

    - name: Install Nginx package
      package:
        name: nginx
        state: present
