---
- name: Install Nginx and Node.js on Ubuntu
  hosts: all
  become: yes  # Run tasks with sudo

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Install Node.js and npm
      apt:
        name: 
          - nodejs
          - npm
        state: present
...