---
- name: Install and configure web server
  apt:
    name: apache2
    state: present

- name: Start the web server
  service:
    name: apache2
    state: started

- name: Copy a simple HTML file
  copy:
    src: index.html
    dest: /var/www/html/
  notify: Restart Apache
...